/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BookNowRouteImport } from './routes/book-now'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServiceSlugRouteImport } from './routes/$serviceSlug'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNowRoute = BookNowRouteImport.update({
  id: '/book-now',
  path: '/book-now',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book-now': typeof BookNowRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/service-areas': typeof ServiceAreasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book-now': typeof BookNowRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/service-areas': typeof ServiceAreasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book-now': typeof BookNowRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$serviceSlug': typeof ServiceSlugRoute
  '/service-areas': typeof ServiceAreasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/apply' | '/book-now' | '/faq' | '/privacy' | '/terms' | '/service-areas' | '/$serviceSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/about' | '/apply' | '/book-now' | '/faq' | '/privacy' | '/terms' | '/service-areas' | '/$serviceSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/book-now'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/$serviceSlug'
    | '/service-areas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  BookNowRoute: typeof BookNowRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-now': {
      id: '/book-now'
      path: '/book-now'
      fullPath: '/book-now'
      preLoaderRoute: typeof BookNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$serviceSlug': {
      id: '/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/$serviceSlug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  BookNowRoute: BookNowRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  ServiceAreasRoute: ServiceAreasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
